<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VectorPilot.Engine</RootNamespace>
    <AssemblyName>VectorPilot.Engine</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VectorPilot.Geometry\VectorPilot.Geometry.csproj" />
    <ProjectReference Include="..\VectorPilot.Serial\VectorPilot.Serial.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>
</Project>
