using System.Globalization;
using System.Text;

namespace VectorPilot.Engine;

/// <summary>Post processor types (ported from PostProcessorType.swift).</summary>
public enum PostProcessorType { Grbl, Universal }

public sealed class PostProcessorTypeInfo
{
    public static string DisplayName(PostProcessorType t) => t switch
    {
        PostProcessorType.Grbl => "GRBL 1.1",
        _ => "Universal G-Code"
    };

    public static string FileExtension(PostProcessorType t) => t switch
    {
        PostProcessorType.Grbl => "gcode",
        _ => "nc"
    };

    /// <summary>Neither GRBL nor Universal handles mid-file tool changes — multi-tool
    /// trees must be split into ordered per-tool files (SPK-FM-R019).</summary>
    public static bool SupportsToolChange(PostProcessorType t) => false;
}

/// <summary>Controller units (ported from GCodeUnits.swift, SPK-0415).</summary>
public enum GCodeUnits { Millimeter, Inch }

public static class GCodeUnitsInfo
{
    public static string ModalCode(GCodeUnits u) => u == GCodeUnits.Millimeter ? "G21" : "G20";
}

/// <summary>Post processor configuration (ported from PostProcessorConfiguration.swift).</summary>
public sealed class PostProcessorConfiguration
{
    public PostProcessorType PostType { get; set; } = PostProcessorType.Grbl;
    public string MachineName { get; set; } = "VectorPilot";
    public string? ToolInfo { get; set; }
    public bool UseLineNumbers { get; set; }
    public bool AbsolutePositioning { get; set; } = true;
    public bool MillimeterUnits { get; set; } = true;
    public bool EnableCoolant { get; set; } = true;
    public double SafeZHeight { get; set; } = 5.0;
    public int ProgramNumber { get; set; } = 1000;
}

/// <summary>Post-processed output (ported from PostProcessedOutput.swift).</summary>
public sealed class PostProcessedOutput
{
    public string GcodeString { get; init; } = "";
    public PostProcessorConfiguration Configuration { get; init; } = new();
    public string FileName => $"toolpath.{PostProcessorTypeInfo.FileExtension(Configuration.PostType)}";
    public int LineCount => GcodeString.Split('\n').Length;
    public int FileSizeBytes => Encoding.UTF8.GetByteCount(GcodeString);
}

/// <summary>
/// Processes raw G-code into controller-ready output with header/footer
/// (ported from GRBLPostProcessor.swift — GRBL 1.1 and Universal flavors).
/// </summary>
public sealed class GRBLPostProcessor
{
    private readonly PostProcessorConfiguration _configuration;

    public GRBLPostProcessor(PostProcessorConfiguration configuration) => _configuration = configuration;

    public static GRBLPostProcessor Grbl(string machineName = "VectorPilot", GCodeUnits units = GCodeUnits.Millimeter)
        => new(new PostProcessorConfiguration
        {
            PostType = PostProcessorType.Grbl,
            MachineName = machineName,
            UseLineNumbers = false,
            AbsolutePositioning = true,
            MillimeterUnits = units == GCodeUnits.Millimeter,
            EnableCoolant = true,
            SafeZHeight = 5.0
        });

    public static GRBLPostProcessor Universal(string machineName = "VectorPilot", GCodeUnits units = GCodeUnits.Millimeter)
        => new(new PostProcessorConfiguration
        {
            PostType = PostProcessorType.Universal,
            MachineName = machineName,
            UseLineNumbers = true,
            AbsolutePositioning = true,
            MillimeterUnits = units == GCodeUnits.Millimeter,
            EnableCoolant = true,
            SafeZHeight = 5.0
        });

    public PostProcessedOutput Process(IReadOnlyList<string> gcodeLines, string? toolInfo = null)
    {
        var lines = new List<string>
        {
            "%",
            $"(Machine: {_configuration.MachineName})",
            $"(Post Processor: {PostProcessorTypeInfo.DisplayName(_configuration.PostType)})"
        };
        if ((toolInfo ?? _configuration.ToolInfo) is { } tool)
        {
            lines.Add($"(Tool: {tool})");
        }
        lines.Add("(Generated by VectorPilot)");
        lines.Add("");
        lines.Add(_configuration.MillimeterUnits ? "G21 ; Set millimeter units" : "G20 ; Set inch units");
        lines.Add(_configuration.AbsolutePositioning ? "G90 ; Absolute positioning" : "G91 ; Relative positioning");
        if (_configuration.EnableCoolant) lines.Add("M8 ; Flood coolant on");
        lines.Add("");

        int lineNumber = 0;
        foreach (var rawLine in gcodeLines)
        {
            var trimmed = rawLine.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('(') || trimmed.StartsWith('%') || trimmed.StartsWith("O="))
            {
                continue;
            }
            if (_configuration.UseLineNumbers)
            {
                lineNumber += 10;
                lines.Add($"{lineNumber}: {trimmed}");
            }
            else
            {
                lines.Add(trimmed);
            }
        }

        lines.Add("");
        lines.Add("M9 ; Coolant off");
        lines.Add($"G0 Z{_configuration.SafeZHeight:0.0} ; Rapid to safe height");
        lines.Add("M2 ; Program end");
        lines.Add("%");

        return new PostProcessedOutput
        {
            GcodeString = string.Join('\n', lines),
            Configuration = _configuration
        };
    }

    public PostProcessedOutput Process(string gcodeString, string? toolInfo = null)
        => Process(gcodeString.Split('\n'), toolInfo);
}
