using System.Globalization;
using System.Text;

namespace VectorPilot.Engine;

/// <summary>
/// Self-contained A4 PDF job-sheet renderer with a structurally valid xref table
/// (job sheet). Deterministic: the only timestamp in the output is
/// JobSheetData.CreatedAt. No NuGet dependencies — pure BCL, ASCII-only output.
/// </summary>
public static class JobSheetPdfRenderer
{
    private const double PageWidth = 595.0;   // A4 portrait, pt
    private const double PageHeight = 842.0;
    private const double Margin = 40.0;
    private const double RightEdge = PageWidth - Margin;

    /// <summary>Render a valid A4 portrait PDF job sheet as bytes.</summary>
    public static byte[] RenderPdf(JobSheetData data)
    {
        string dateStr = data.CreatedAt.ToString("MMM d, yyyy h:mm tt", CultureInfo.InvariantCulture);
        string footerStr = $"Generated by VectorPilot - {dateStr}";

        var content = new StringBuilder();

        void Text(string font, double size, double x, double y, string text)
        {
            content.Append("BT\n");
            content.Append('/').Append(font).Append(' ').Append(F(size)).Append(" Tf\n");
            content.Append(F(x)).Append(' ').Append(F(y)).Append(" Td\n");
            content.Append('(').Append(Escape(text)).Append(") Tj\n");
            content.Append("ET\n");
        }

        void Line(double x1, double y1, double x2, double y2)
        {
            content.Append(F(x1)).Append(' ').Append(F(y1)).Append(" m\n");
            content.Append(F(x2)).Append(' ').Append(F(y2)).Append(" l\nS\n");
        }

        void Rect(double x, double y, double w, double h)
        {
            content.Append(F(x)).Append(' ').Append(F(y)).Append(' ')
                   .Append(F(w)).Append(' ').Append(F(h)).Append(" re S\n");
        }

        // Title line: job name, 16pt bold.
        Text("F2", 16, Margin, 790, data.JobName);

        // Meta lines.
        Text("F1", 10, Margin, 758, $"Material: {data.Material}");
        Text("F1", 10, Margin, 740, $"Sheet Size: {F(data.SheetWidth)} x {F(data.SheetHeight)} mm");
        Text("F1", 10, Margin, 722, $"Date: {dateStr}");

        // Toolpath table.
        Text("F2", 12, Margin, 690, "Toolpaths");

        double headerY = 660;
        double rowPitch = 14;
        Line(Margin, headerY + 12, RightEdge, headerY + 12); // rule above header
        Line(Margin, headerY - 6, RightEdge, headerY - 6);   // rule below header

        var cols = new (double X, double W)[]
        {
            (40, 120), (160, 70), (230, 100), (330, 80), (410, 70), (480, 75)
        };
        var headers = new[] { "Name", "Type", "Tool", "Feed (mm/min)", "Depth (mm)", "Time (min)" };
        for (int c = 0; c < headers.Length; c++)
        {
            Text("F2", 9, cols[c].X, headerY, headers[c]);
        }

        double lastRowY = headerY;
        for (int i = 0; i < data.Toolpaths.Count; i++)
        {
            var tp = data.Toolpaths[i];
            lastRowY = headerY - rowPitch * (i + 1);
            var cells = new[]
            {
                tp.Name,
                JobSheetToolpathTypeInfo.DisplayName(tp.Type),
                tp.Tool,
                tp.FeedRate.ToString("0", CultureInfo.InvariantCulture),
                tp.Depth.ToString("0.00", CultureInfo.InvariantCulture),
                (tp.EstimatedTime / 60.0).ToString("0.0", CultureInfo.InvariantCulture)
            };
            for (int c = 0; c < cells.Length; c++)
            {
                Text("F1", 9, cols[c].X, lastRowY, cells[c]);
            }
        }
        Line(Margin, lastRowY - 7, RightEdge, lastRowY - 7); // rule below the last row

        // Notes box.
        double notesLabelY = lastRowY - 25;
        Text("F2", 12, Margin, notesLabelY, "Notes");
        double boxTop = notesLabelY - 8;
        const double boxHeight = 70;
        double boxBottom = boxTop - boxHeight;
        Rect(Margin, boxBottom, RightEdge - Margin, boxHeight);
        if (!string.IsNullOrEmpty(data.Notes))
        {
            Text("F1", 9, Margin + 6, boxTop - 14, data.Notes);
        }

        // Footer line.
        Text("F1", 8, Margin, 30, footerStr);

        string contentStream = content.ToString();

        var objects = new StringBuilder();
        objects.Append("%PDF-1.4\n");
        objects.Append("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
        objects.Append("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
        objects.Append("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources 5 0 R /Contents 4 0 R >>\nendobj\n");
        objects.Append($"4 0 obj\n<< /Length {contentStream.Length} >>\nstream\n{contentStream}endstream\nendobj\n");
        objects.Append("5 0 obj\n<< /Font << /F1 6 0 R /F2 7 0 R >> >>\nendobj\n");
        objects.Append("6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n");
        objects.Append("7 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n");

        string text = objects.ToString();
        int xrefOffset = text.Length; // all-ASCII output: chars == bytes

        // Byte offsets of each object header (ASCII, so string index == byte offset).
        var offsets = new List<int>(7);
        for (int i = 1; i <= 7; i++)
        {
            offsets.Add(text.IndexOf($"{i} 0 obj", StringComparison.Ordinal));
        }

        var sb = new StringBuilder(text);
        sb.Append("xref\n0 8\n0000000000 65535 f \n");
        foreach (int off in offsets)
        {
            sb.Append($"{off:0000000000} 00000 n \n");
        }
        sb.Append("trailer\n<< /Size 8 /Root 1 0 R >>\nstartxref\n");
        sb.Append(xrefOffset);
        sb.Append("\n%%EOF");

        return Encoding.ASCII.GetBytes(sb.ToString());
    }

    /// <summary>Round coordinates to 1 decimal place, invariant culture.</summary>
    private static string F(double v) => v.ToString("0.0", CultureInfo.InvariantCulture);

    /// <summary>Escape PDF literal-string special characters.</summary>
    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
}
