using System.Globalization;
using System.Text;

namespace VectorPilot.Engine;

/// <summary>Toolpath type shown on the job sheet (ported from ToolpathInfo.ToolpathType).</summary>
public enum JobSheetToolpathType { Profile, Pocket, Drill, VCarve, QuickEngrave }

public static class JobSheetToolpathTypeInfo
{
    public static string DisplayName(JobSheetToolpathType t) => t switch
    {
        JobSheetToolpathType.Profile => "Profile",
        JobSheetToolpathType.Pocket => "Pocket",
        JobSheetToolpathType.Drill => "Drill",
        JobSheetToolpathType.VCarve => "V-Carve",
        _ => "Quick Engrave"
    };
}

/// <summary>A single toolpath row on the job sheet (ported from ToolpathInfo.swift).</summary>
public sealed class ToolpathInfo
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public string Name { get; init; } = "";
    public JobSheetToolpathType Type { get; init; }
    public string Tool { get; init; } = "";
    public double FeedRate { get; init; }   // mm/min
    public double Depth { get; init; }      // mm
    public double EstimatedTime { get; init; } // seconds
}

/// <summary>Job sheet summary data (ported from JobSheetData.swift).</summary>
public sealed class JobSheetData
{
    public string JobName { get; init; } = "";
    public string Material { get; init; } = "";
    public double SheetWidth { get; init; }  // mm
    public double SheetHeight { get; init; } // mm
    public List<ToolpathInfo> Toolpaths { get; init; } = new();
    public DateTime CreatedAt { get; init; } = DateTime.Now;
    public string Notes { get; init; } = "";
}

/// <summary>
/// Minimal-PDF job sheet generator (ported from JobSheetGenerator.swift — but
/// with correct xref offsets; the Swift leaves zero placeholders).
/// </summary>
public static class JobSheetGenerator
{
    public static string BuildPdf(JobSheetData data)
    {
        string dateStr = data.CreatedAt.ToString("MMM d, yyyy h:mm tt", CultureInfo.InvariantCulture);
        string footerStr = $"Generated by ShopPilot — {DateTime.Now.ToString("MMM d, yyyy h:mm tt", CultureInfo.InvariantCulture)}";

        var content = new StringBuilder();
        void Text(string font, double size, double x, double y, string text)
        {
            content.Append($"BT\n/{font} {size.ToString("0", CultureInfo.InvariantCulture)} Tf\n{x.ToString("0", CultureInfo.InvariantCulture)} {y.ToString("0", CultureInfo.InvariantCulture)} Td\n({Escape(text)}) Tj\nET\n");
        }

        Text("F1", 18, 0, 0, data.JobName);
        Text("F1", 12, 0, 0, "Job Sheet");
        Text("F1", 10, 0, -25, "Job:");
        Text("F2", 10, 50, -25, data.JobName);
        Text("F1", 10, 0, -15, "Material:");
        Text("F2", 10, 65, -15, data.Material);
        Text("F1", 10, 0, -15, "Sheet Size:");
        Text("F2", 10, 75, -15, $"{data.SheetWidth:0.0} x {data.SheetHeight:0.0} mm");
        Text("F1", 10, 0, -15, "Date:");
        Text("F2", 10, 40, -15, dateStr);
        Text("F1", 10, 0, -30, "Toolpaths");

        var headers = new[] { "Name", "Type", "Tool", "Feed (mm/min)", "Depth (mm)", "Time (min)" };
        double headerY = -50;
        double x = 30;
        foreach (var header in headers)
        {
            Text("F1", 9, x, headerY, header);
            x += 80;
        }

        for (int i = 0; i < data.Toolpaths.Count; i++)
        {
            var tp = data.Toolpaths[i];
            double rowY = headerY - 15 * (i + 1);
            double cx = 30;
            foreach (var cell in new[]
            {
                tp.Name,
                JobSheetToolpathTypeInfo.DisplayName(tp.Type),
                tp.Tool,
                tp.FeedRate.ToString("0", CultureInfo.InvariantCulture),
                tp.Depth.ToString("0.00", CultureInfo.InvariantCulture),
                (tp.EstimatedTime / 60.0).ToString("0.0", CultureInfo.InvariantCulture)
            })
            {
                Text("F2", 9, cx, rowY, cell);
                cx += 80;
            }
        }

        Text("F1", 10, 0, -25, "Notes");
        if (!string.IsNullOrEmpty(data.Notes)) Text("F2", 9, 0, -15, data.Notes);
        Text("F1", 8, 0, -30, footerStr);

        string contentStream = content.ToString();

        var objects = new StringBuilder();
        objects.AppendLine("%PDF-1.4");
        objects.AppendLine("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj");
        objects.AppendLine("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj");
        objects.AppendLine($"3 0 obj\n<< /Length {contentStream.Length} >>\nstream\n{contentStream}endstream\nendobj");
        objects.AppendLine("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj");
        objects.AppendLine("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding /FontDescriptor 6 0 R >>\nendobj");
        objects.AppendLine("6 0 obj\n<< /Type /FontDescriptor /FontName /Helvetica /Flags 32 /ItalicAngle 0 /Ascent 750 /Descent -250 /CapHeight 750 /AvgWidth 400 /MaxWidth 800 /FontWeight 400 /StemV 40 >>\nendobj");

        string text = objects.ToString();
        int xrefOffset = text.Length; // ASCII
        var offsets = new List<int>();
        for (int i = 1; i <= 6; i++)
        {
            offsets.Add(text.IndexOf($"{i} 0 obj", StringComparison.Ordinal));
        }

        var sb = new StringBuilder(text);
        sb.Append($"xref\n0 {offsets.Count + 1}\n0000000000 65535 f \n");
        foreach (var off in offsets)
        {
            sb.Append($"{off:0000000000} 00000 n \n");
        }
        sb.Append($"trailer\n<< /Size {offsets.Count + 1} /Root 1 0 R >>\nstartxref\n{xrefOffset}\n%%EOF\n");
        return sb.ToString();
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
}
