using System.Globalization;

namespace VectorPilot.Engine;

/// <summary>
/// HTML job-sheet template engine (ported from JobSheetHTMLTemplateEngine.swift,
/// SPK-1135): bundled A4 template filled with {{PLACEHOLDER}} tokens; pure
/// string substitution so it is fully testable. The filled HTML renders to
/// PDF in the app layer.
/// </summary>
public static class JobSheetHTMLTemplateEngine
{
    public const string BundledTemplate = """
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset="utf-8">
        <style>
          @page { size: A4; margin: 18mm; }
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 11pt; }
          h1 { font-size: 17pt; margin: 0 0 2mm 0; }
          .subtitle { color: #666; font-size: 10pt; margin-bottom: 6mm; }
          table { border-collapse: collapse; width: 100%; margin-top: 5mm; }
          th, td { border: 1px solid #bbb; padding: 2mm 3mm; text-align: left; font-size: 9.5pt; }
          th { background: #f0f0f0; }
          .meta { display: grid; grid-template-columns: 30mm 60mm 30mm 60mm; row-gap: 1.5mm; margin-top: 4mm; }
          .meta .label { color: #666; }
          .notes { margin-top: 6mm; }
          .notes p { border: 1px solid #ccc; min-height: 20mm; padding: 3mm; }
          .footer { margin-top: 8mm; color: #999; font-size: 8.5pt; border-top: 1px solid #ddd; padding-top: 2mm; }
        </style>
        </head>
        <body>
          <h1>{{JOB_NAME}}</h1>
          <div class="subtitle">Job Sheet — VectorPilot</div>
          <div class="meta">
            <span class="label">Material</span><span>{{MATERIAL}}</span>
            <span class="label">Sheet size</span><span>{{SHEET_WIDTH}} × {{SHEET_HEIGHT}} mm</span>
            <span class="label">Date</span><span>{{DATE}}</span>
            <span class="label">Toolpaths</span><span>{{TOOLPATH_COUNT}}</span>
          </div>
          <table>
            <thead>
              <tr><th>Name</th><th>Type</th><th>Tool</th><th>Feed (mm/min)</th><th>Depth (mm)</th><th>Time (min)</th></tr>
            </thead>
            <tbody>
            {{TOOLPATH_ROWS}}
            </tbody>
          </table>
          <div class="notes">
            <span class="label">Notes</span>
            <p>{{NOTES}}</p>
          </div>
          <div class="footer">{{FOOTER}}</div>
        </body>
        </html>
        """;

    public static string ToolpathRows(IReadOnlyList<ToolpathInfo> toolpaths)
        => string.Join("\n", toolpaths.Select(tp =>
            $"<tr><td>{Escape(tp.Name)}</td><td>{Escape(JobSheetToolpathTypeInfo.DisplayName(tp.Type))}</td>" +
            $"<td>{Escape(tp.Tool)}</td><td>{tp.FeedRate:0}</td>" +
            $"<td>{tp.Depth:0.00}</td>" +
            $"<td>{tp.EstimatedTime / 60.0:0.0}</td></tr>"));

    public static string Fill(JobSheetData data) => Fill(data, BundledTemplate);

    public static string Fill(JobSheetData data, string template)
    {
        var date = data.CreatedAt.ToString("g", CultureInfo.InvariantCulture);
        var replacements = new Dictionary<string, string>
        {
            ["{{JOB_NAME}}"] = Escape(data.JobName),
            ["{{MATERIAL}}"] = Escape(data.Material),
            ["{{SHEET_WIDTH}}"] = data.SheetWidth.ToString("0.0", CultureInfo.InvariantCulture),
            ["{{SHEET_HEIGHT}}"] = data.SheetHeight.ToString("0.0", CultureInfo.InvariantCulture),
            ["{{DATE}}"] = Escape(date),
            ["{{NOTES}}"] = Escape(data.Notes),
            ["{{TOOLPATH_COUNT}}"] = data.Toolpaths.Count.ToString(),
            ["{{TOOLPATH_ROWS}}"] = ToolpathRows(data.Toolpaths),
            ["{{FOOTER}}"] = Escape($"Generated by VectorPilot — {DateTime.Now:g}")
        };
        var out_ = template;
        foreach (var (token, value) in replacements)
        {
            out_ = out_.Replace(token, value);
        }
        return out_;
    }

    public static string Escape(string s)
        => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
             .Replace("\"", "&quot;").Replace("'", "&#39;");
}
